spring:
  datasource:
    url: jdbc:mysql://112.74.161.146:3306/demo?characterEncoding=utf8&useSSL=true
    username: root
    password: root.root123
    driverClassName: com.mysql.cj.jdbc.Driver
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  webflux:
    static-path-pattern: /templates/**
  resources:
    static-locations: classpath:/
mybatis:
  mapper-locations: classpath:/mapper/*.xml

#logging.level.org.activiti.engine.impl.persistence.entity: debug

server:
  port: 8700
  tomcat:
    uri-encoding: UTF-8
